### ISSUE TITLE
crash when loading from cache

### ISSUE THREAD

**Issue by mecrip** [mecrip/homebridge-playbulb#1]
homebridge crash when loading:

1. a bulb is present in the cache
2.   `this.api.unregisterPlatformAccessories("homebridge-playbulb", "Playbulb", [homebridgeAcc]);` is called
3. scanning begins
4. same accessory is detected
5. `this.api.registerPlatformAccessories("homebridge-playbulb",` "Playbulb", [homebridgeAcc]); `cause crash

> 
> Aug 19 22:12:36 myberry homebridge[15307]: [2017-8-19 22:12:36] Homebridge is running on port 51826.
> Aug 19 22:12:36 myberry homebridge[15307]: [2017-8-19 22:12:36] Scanning will be (re)started
> Aug 19 22:12:36 myberry homebridge[15307]: [2017-8-19 22:12:36] Discovered bulb on address c2:9d:4b:16:ac:e6. Will connect.
> Aug 19 22:12:37 myberry homebridge[15307]: /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:225
> Aug 19 22:12:37 myberry homebridge[15307]: throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
> Aug 19 22:12:37 myberry homebridge[15307]: ^
> Aug 19 22:12:37 myberry homebridge[15307]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 034f3f96-3c30-4e22-a906-39f212ec53b4
> Aug 19 22:12:37 myberry homebridge[15307]: at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:225:13)
> Aug 19 22:12:37 myberry homebridge[15307]: at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:251:10)
> Aug 19 22:12:37 myberry homebridge[15307]: at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:437:16)
> Aug 19 22:12:37 myberry homebridge[15307]: at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
> Aug 19 22:12:37 myberry homebridge[15307]: at emitOne (events.js:115:13)
> Aug 19 22:12:37 myberry homebridge[15307]: at API.emit (events.js:210:7)
> Aug 19 22:12:37 myberry homebridge[15307]: at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
> Aug 19 22:12:37 myberry homebridge[15307]: at PlaybulbPlatform.connectCandle (/home/pi/homebridge-playbulb/index.js:95:14)
> Aug 19 22:12:37 myberry homebridge[15307]: at PlaybulbPlatform.<anonymous> (/home/pi/homebridge-playbulb/index.js:79:18)
> Aug 19 22:12:37 myberry homebridge[15307]: at Peripheral.<anonymous> (/home/pi/homebridge-playbulb/node_modules/noble/lib/peripheral.js:38:7)
> 

> 

.

**Comment by mecrip** [comment]
Seems a bug in homebridge, with unregister accessory not completing before registeracessory
